# Generated by Django 3.2.7 on 2021-10-04 19:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('nota', models.IntegerField()),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y')),
                ('date_post', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
